## 0. Mengimport Modul dan Membaca Data

In [ ]:
# Basic Packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Classifier or Clustering algorithm
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans
from sklearn.cluster import Birch
from sklearn.mixture import GaussianMixture
# Metrics
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import average_precision_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

In [6]:
# Data asli untuk training: data hasil oversampling dari Bagian 2
X_train = pd.read_csv('(FINAL) Oversampling Graph-based.csv').drop(['Unnamed: 0'], axis=1)
X_train.columns = ['category_es_barsandrestaurants',
       'category_es_contents', 'category_es_fashion', 'category_es_food',
       'category_es_health', 'category_es_home', 'category_es_hotelservices',
       'category_es_hyper', 'category_es_leisure', 'category_es_otherservices',
       'category_es_sportsandtoys', 'category_es_tech',
       'category_es_transportation', 'category_es_travel',
       'category_es_wellnessandbeauty', 'amount', 'age', 'gender']
X_train = X_train.iloc[:, [16,17,15,0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]]
y_train = pd.read_csv('(FINAL) Oversampling Graph-based label.csv')['0']

# Data asli untuk testing: Data asli dari Bagian 1
X_test = pd.read_csv('BankSim 8000.csv')
X_test = pd.get_dummies(X_test.drop(['Unnamed: 0', 'step', 'customer', 'merchant','fraud'], axis=1), columns=['category'])
X_test = X_test.div(X_test.sum(axis=1), axis=0) # Normalisasi
y_test = pd.read_csv('BankSim 8000 2.csv')['fraud']

# Data Embedding AAVGA untuk training dan testing: hasil dari Bagian 2
Xe_train =  pd.read_csv('(FINAL) Embedding 32D with ImbalanceSampler (training set).csv').drop(['Unnamed: 0'], axis=1)
Xe_test = pd.read_csv('(FINAL) Embedding 32D with ImbalanceSampler.csv').drop(['Unnamed: 0'], axis=1)
ye_train = y_train
ye_test = y_test

## 1. Hasil dengan model AAVGA

In [18]:
classifier = MLPClassifier(random_state=42)
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

0.989
0.555
0.104
[[7898    2]
 [  89   11]]


In [19]:
classifier = SVC(random_state=42)
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

0.988
0.5
0.012
[[7900    0]
 [ 100    0]]


In [20]:
classifier = LogisticRegression(random_state=42)
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

0.988
0.5
0.012
[[7900    0]
 [ 100    0]]


In [21]:
classifier = KNeighborsClassifier()
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

0.992
0.764
0.396
[[7881   19]
 [  47   53]]


In [22]:
classifier = DecisionTreeClassifier(random_state=42)
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

1.0
0.995
0.99
[[7900    0]
 [   1   99]]


In [23]:
classifier = xgb.XGBClassifier(random_state=42)
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

1.0
1.0
1.0
[[7900    0]
 [   0  100]]


In [24]:
classifier = KMeans(n_clusters=2)
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

0.864
0.931
0.084
[[6808 1092]
 [   0  100]]


In [25]:
classifier = GaussianMixture(n_components=2)
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

0.863
0.931
0.083
[[6802 1098]
 [   0  100]]


In [25]:
classifier = GaussianMixture(n_components=2)
clf_output = classifier.fit(Xe_test, ye_test)
pred = classifier.predict(Xe_test)
print(np.round(accuracy_score(ye_test, pred), 3))
print(np.round(roc_auc_score(ye_test, pred), 3))
print(np.round(average_precision_score(ye_test, pred), 3))
print(confusion_matrix(ye_test, pred))

0.863
0.931
0.083
[[6802 1098]
 [   0  100]]


## 2. Hasil dengan Direct ML

In [30]:
classifier = MLPClassifier(random_state=42)
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

0.971
0.956
0.278
[[7675  225]
 [   6   94]]


C:\Users\nural\anaconda3\envs\geom\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [31]:
classifier = SVC(random_state=42)
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

0.944
0.932
0.159
[[7457  443]
 [   8   92]]


In [32]:
classifier = LogisticRegression(random_state=42)
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

0.932
0.912
0.13
[[7371  529]
 [  11   89]]


In [33]:
classifier = KNeighborsClassifier()
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

0.991
0.995
0.575
[[7826   74]
 [   0  100]]


In [34]:
classifier = DecisionTreeClassifier(random_state=42)
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

1.0
1.0
1.0
[[7900    0]
 [   0  100]]


In [35]:
classifier = xgb.XGBClassifier(random_state=42)
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

1.0
1.0
0.962
[[7896    4]
 [   0  100]]


In [36]:
classifier = KMeans(n_clusters=2)
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

0.814
0.417
0.012
[[6509 1391]
 [  99    1]]


In [61]:
classifier = GaussianMixture(n_components=2)
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test) == 0
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

0.872
0.535
0.014
[[6959  941]
 [  81   19]]


In [38]:
classifier = Birch(threshold=0.03, n_clusters=2)
clf_output = classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
print(np.round(accuracy_score(y_test, pred), 3))
print(np.round(roc_auc_score(y_test, pred), 3))
print(np.round(average_precision_score(y_test, pred), 3))
print(confusion_matrix(y_test, pred))

0.943
0.477
0.012
[[7544  356]
 [ 100    0]]
